### ISSUE TITLE
Update the geoiplite dataset we ship

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-geoip#11]
The current one we ship is from January 2013

**Comment by electrical** [comment]
Need to create a jenkins job that fetches the vendor files periodically ( every 2 weeks or so )

**Comment by russorat** [comment]
+1

**Comment by markwalkom** [comment]
From http://dev.maxmind.com/geoip/legacy/geolite/;
> New Database Format Available: This page is for our legacy databases. For our latest database format, please see our GeoLite2 Databases.

The new packages are [here](http://dev.maxmind.com/geoip/geoip2/geolite2/) and appear to be in a different format as (per the quote) and not directly compatible with LS.

**Comment by christofhaerens** [comment]
+1

**Comment by KrisBuytaert** [comment]
+2

**Comment by suyograo** [comment]
GeoIP2 and IPv6 support has been added in version 3.0.0 of this plugin for LS versions <= 2.x and 4.0.0 for LS version >= 5.x. Many thanks to @garyelephant and @ebuildy for helping out!
