### ISSUE TITLE
How to switch the logstash case to avoid losing the data in the logstash mem

### ISSUE THREAD

**Issue by liuzhenji** [logstash-plugins/logstash-filter-geoip#114]
Cause maybe, there already are some log datas in the logstath which have not transoported to the ES.Therefore how to make it...

**Comment by jordansissel** [comment]
I don't understand the question, but it seems like a question about data delivery, not geoip filter.

 Can you ask on https://discuss.elastic.co/ ?

**Comment by liuzhenji** [comment]
yeah,I'll ask on [https://discuss.elastic.co/](https://discuss.elastic.co/).
But I've already solved this problem.Cause when I shut down the logstash, there will be a log like
this:  ....signal    which means there may be a "pre-fetch" mechanism in data delivery.
