### ISSUE TITLE
SHA1 database doesn't match

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-filter-geoip#117]
The database seem out of date, can we find a more long term solution?

```
SHA1 does not match (expected '69d209236a96f2a3f27de30c6cf954b56edb916e' but got 'dc594fb45880bb33767f3280f2f108389f24db22')
```

https://travis-ci.org/logstash-plugins/logstash-filter-geoip

**Comment by jsvd** [comment]
I'll update the sha for now. the site provides an md5 checksum, so maybe we could use that instead of hardcoding the checksum in a local file.
