### ISSUE TITLE
Natively support IPv6 address lookups

### ISSUE THREAD

**Issue by tylerjl** [logstash-plugins/logstash-filter-geoip#12]
The geoip filter works great for IPv4 lookups, but there's a couple of IPv6 addresses on the internet, and we'd like to be able to look those up, too. :+1:

[Maxmind provides IPv6 databases](http://dev.maxmind.com/geoip/legacy/geolite/), and the filter provides a `database` option, so while this can be done manually by dropping the IPv6 database onto a machine and adding logic to use the correct database, it would certainly be nice to at least bundle it along with v4 database in the plugin so that one could change the database setting to the IPv6 one explicitly after doing some regex catching:

    if [ip] =~ /:/ {
        geoip {
            database => "GeoLiteCityv6.dat"
            ...
        }
    } else {
        geoip {
            ...
        }
    }

*or*, the filter could handle it transparently if it's feeling ambitious and detect the address type within the plugin itself and make life even better for everyone.

**Comment by untergeek** [comment]
Migrating https://logstash.jira.com/browse/LOGSTASH-1100 from JIRA.

**Comment by archimedesdev** [comment]
Hi, just curious if there's been any progress or traction on this request. Thanks!

**Comment by untergeek** [comment]
It's important to us, but please pardon the delays while we prioritize the release of Logstash 1.5.

**Comment by TinLe** [comment]
I believe this is already fixed.   Did the PR not get merged?

https://github.com/logstash-plugins/logstash-filter-geoip/pull/8

**Comment by untergeek** [comment]
Not yet, no.

**Comment by Deshke** [comment]
any update on this ?

**Comment by goacid** [comment]
Ping

**Comment by SamSaffron** [comment]
@untergeek any news here, its a 1 line change ... :(

**Comment by untergeek** [comment]
We're busy refactoring all plugins to do work differently for 2.0.  Also, a refactor of the plugin to use the newer database format is pending.  This change will probably not be added until then.

**Comment by hanej** [comment]
+1

**Comment by IngaFeick** [comment]
+1

**Comment by sdsunjay** [comment]
+1

**Comment by killafunkinmofo** [comment]
+1

**Comment by panda87** [comment]
+1

**Comment by pemontto** [comment]
:+1:

**Comment by userguy** [comment]
any update on This .. The Geoip is not able to look at Maxmind database for ipv6

**Comment by SamSaffron** [comment]
We use a patched up version to get this working, something along the lines of:

```
 ruby {
      code => "
        require 'ipaddr' unless defined?(IPAddr)
        if event['client_ip']
           ip = IPAddr.new(event['client_ip'])
           event['client_ip_v4'] = ip.to_s if ip.ipv4?
           event['client_ip_v6'] = ip.to_s if ip.ipv6?
        end

        if event['client_ip_v6']
          db = Thread.current['geoip_v6_db'] ||= ::GeoIP.new('/logstash/GeoLiteCityv6.dat')
          geoip = db.city(event['client_ip_v6'])

          if geoip
            clean = {}
            geoip = geoip.to_hash
            if geoip.key?(:latitude) && geoip.key?(:longitude)
              clean['location'] = [geoip[:longitude].to_f, geoip[:latitude].to_f]
            end

            geoip.each do |k,v|
              next if v.nil? || ((String===v) && v.empty?)
              clean[k.to_s] = v
            end

            event['geoip'] = clean
          end
        end
        "
    }
```

works like a charm but really should be built in @untergeek

**Comment by omercnet** [comment]
+1

**Comment by suyograo** [comment]
GeoIP2 and IPv6 support has been added in version 3.0.0 of this plugin for LS versions <= 2.x and 4.0.0 for LS version >= 5.x. Many thanks to @garyelephant and @ebuildy for helping out!

**Comment by Deshke** [comment]
do we need to change something on the parser ? 

`
 "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [geoip.ip]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse ip [2xyz:abcd:a0:7130:0:0:0:2], not a valid ipv4 address (4 dots)"}}}}, :level=>:warn}`

**Comment by webmstr** [comment]
@Deshke, did you find a solution?

**Comment by jordansissel** [comment]
@Deshke your field "geoip.ip" is mapped to an `ip` in Elasticsearch, which doesn't support ipv6 addresses (only ipv4)

**Comment by webmstr** [comment]
@jordansissel so if we want ipv6 geoip lookup, what's the solution?  Put the ipv6 value in some other field and erase the geoip.ip field before shipping to elasticsearch?

**Comment by jordansissel** [comment]
@webmstr For now, you'll have to make Elasticsearch use a `string` mapping, not an `ip` mapping. That is, until you upgrade to Elasticsearch 5.0.0 (not released yet) which [added support for IPv6](https://github.com/elastic/elasticsearch/pull/17746).

**Comment by Deshke** [comment]
oh dear god, that will break things...

**Comment by jordansissel** [comment]
I mean, you could store the ipv6 address in a separate field from the other ipv4 addresses if that helps.

**Comment by webmstr** [comment]
Just following up...  the v3 plugin works fine with the maxmind geoip2 database.  I ended up removing the geoip.ip field after the geoip{} filter call if the value was ipv6, to keep ES happy until it supports ipv6 addresses:

            if [geoip][ip] =~ /:/ {
                mutate {
                    remove_field => [ "[geoip][ip]" ]
                }
            }

**Comment by czerasz** [comment]
Here are my observations:

- running a Docker container from the `logstash:5.0.0-alpha4-1` image

  with this config:
  ```
  geoip {
    source => "clientip"
    target => "geoip"
    database => "/usr/share/geolite/GeoLite2-City.mmdb"
  }
  ```

  Runs fine. The `GeoLite2` databases have already IPv6 support build in.

- running a Docker container from the `logstash:2.3.4-1` image

  with this config:
  ```
  if [clientip] =~ /:/ {
    geoip {
      source => "clientip"
      target => "geoip"
      database => "/usr/share/geolite/GeoLiteCityv6.dat"
    }
  } else {
    geoip {
      source => "clientip"
      target => "geoip"
      database => "/usr/share/geolite/GeoLite2-City.mmdb"
    }
  }
  ```

  throws this:
  ```
  {
    :timestamp=>"2016-07-15T06:50:42.672000+0000",
    :message=>"Pipeline aborted due to error",
    :exception=>#<NameError: uninitialized constant LogStash::Filters::GeoIP::RuntimeException>,
    :backtrace=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-2.0.7/lib/logstash/filters/geoip.rb:114:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:182:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:182:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'"],
    :level=>:error
  }
  ```

- running a Docker container from the `logstash:5.0.0-alpha4-1` image

  with this config:
  ```
  if [clientip] =~ /:/ {
    geoip {
      source => "clientip"
      target => "geoip"
      database => "/usr/share/geolite/GeoLiteCityv6.dat"
    }
  } else {
    geoip {
      source => "clientip"
      target => "geoip"
      database => "/usr/share/geolite/GeoLite2-City.mmdb"
    }
  }
  ```

  throws this:
  ```
  {
    :timestamp=>"2016-07-15T06:55:33.199000+0000",
    :message=>"Pipeline aborted due to error",
    :exception=>com.maxmind.db.InvalidDatabaseException: Could not find a MaxMind DB metadata marker in this file (GeoLiteCityv6.dat). Is this a valid MaxMind DB file?,
    :backtrace=>["com.maxmind.db.Reader.findMetadataStart(com/maxmind/db/Reader.java:278)", "com.maxmind.db.Reader.<init>(com/maxmind/db/Reader.java:129)", "com.maxmind.db.Reader.<init>(com/maxmind/db/Reader.java:116)", "com.maxmind.geoip2.DatabaseReader.<init>(com/maxmind/geoip2/DatabaseReader.java:37)", "com.maxmind.geoip2.DatabaseReader.<init>(com/maxmind/geoip2/DatabaseReader.java:27)", "com.maxmind.geoip2.DatabaseReader$Builder.build(com/maxmind/geoip2/DatabaseReader.java:133)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "RUBY.register(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.0.0-java/lib/logstash/filters/geoip.rb:141)", "RUBY.suppress_all_warnings(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.0.0-java/lib/logstash/filters/geoip.rb:21)", "RUBY.register(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-4.0.0-java/lib/logstash/filters/geoip.rb:128)", "RUBY.register(/usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201)", "RUBY.start_workers(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:185)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)", "RUBY.start_workers(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:185)", "RUBY.run(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:139)", "RUBY.start_pipeline(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:240)", "java.lang.Thread.run(java/lang/Thread.java:745)"],
    :level=>:error
  }
  ```

**Comment by ebuildy** [comment]
Can you try to install logstash-filter-geoip2 ? Configuration alias is
geoip2. Cheers

**Comment by czerasz** [comment]
@ebuildy thanks for the tip!

With the `geoip2` filter installed (`logstash-plugin install logstash-filter-geoip2`) both IPv4 and IPv6 are working fine.

Here is the config:

```
geoip2 {
  source => "clientip"
  target => "geoip"
  database => "/usr/share/geolite/GeoLite2-City.mmdb"
}
```

Tested with:

- tested with `logstash 2.3.4`
- [GeoLite2-City.mmdb](http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz )

**Comment by weliketomarty** [comment]
This was helpful everyone, thanks.

One last requirement on my end, ASN. The [GeoIP2 City](https://dev.maxmind.com/geoip/geoip2/geoip2-city-country-csv-databases/) database does not include geoip.asn & geoip.number.

The following works with the comments (uncommenting out the IPv6 if statement causes the same errors seen before)

```
    geoip2 {
      source => "src_ip"
      database => "/etc/logstash/GeoLite2-City.mmdb"
    }
#    if [src_ip] =~ /:/ {
#      geoip {
#      source => "src_ip"
#      database => "/etc/logstash/GeoIPASNumv6.dat"
#      }
#    } else {
      geoip {
      source => "src_ip"
      database => "/etc/logstash/GeoIPASNum.dat"
      }
#    }
```

Error when uncommenting out the ipv6 if statement


> {:timestamp=>"2016-08-02T17:57:27.357000-0400", :message=>"Pipeline aborted due to error", :exception=>#<NameError: uninitialized constant LogStash::Filters::GeoIP::RuntimeException>, :backtrace=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-2.0.7/lib/logstash/filters/geoip.rb:114:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:182:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:182:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}

So the only thing missing is ASN for IPv6.

Any suggestions would be appreciated.
