### ISSUE TITLE
Add option to choose default database that we load

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-filter-geoip#126]
- [x] Include new GeoIPLite-ASN database by default. It adds 5mb to the downloadable, which is a bummer, but LS default download size is already big.
- [x] Add new option called `default_database_type` to choose a default database. Options include  `GeoIPLite-City` or `GeoIPLite-ASN`.

**Comment by untergeek** [comment]
https://github.com/logstash-plugins/logstash-filter-geoip/pull/127 should cover this.
