### ISSUE TITLE
add ECS compliant country_iso_code

### ISSUE THREAD

**Issue by graphaelli** [logstash-plugins/logstash-filter-geoip#155]
Country code information is stored in country_code2 (and country_code3) while ECS dictates use of `country_iso_code`.  I'm not familiar with how plugins are versioned but I expect this field could be added immediately and the non-ECS removed later?

city db:
https://github.com/logstash-plugins/logstash-filter-geoip/blob/14676d9f4408862163c327be597fa882b4753983/src/main/java/org/logstash/filters/GeoIPFilter.java#L232-L243

country db:
https://github.com/logstash-plugins/logstash-filter-geoip/blob/14676d9f4408862163c327be597fa882b4753983/src/main/java/org/logstash/filters/GeoIPFilter.java#L316-L321

related to #92.

**Comment by ragri8** [comment]
Same thing with region_code which is referenced by `region_iso_code` in ECS.

The geoip processor available for ingest node already use `country_iso_code` and `region_iso_code` to store country and region codes informations.

Adding those fields shouldn't cause any issue for anyone and won't require a lot of work. I'm in favor for this issue to be solved and pushed as soon as possible, if anyone is willing to take it.

**Comment by kares** [comment]
@kaisecheng I think this is fully resolved by now and we can close the issue, right?

**Comment by kaisecheng** [comment]
@kares Thanks for checking this issue. Yes, `country_code2` has mapped to `geo.country_iso_code` and `country_code3` is removed in ECS. Hence, close the issue.
