### ISSUE TITLE
Update fails - undefined method `ungz'

### ISSUE THREAD

**Issue by rabidscorpio** [logstash-plugins/logstash-filter-geoip#16]
I'm trying to update all the gems that come with logstash 1.5 beta1 and this gem fails with the error below.  How do I skip a gem when I'm trying to update all the gems?  Otherwise, I'm going to have to list every single gem I want to update.

NoMethodError: undefined method `ungz' for LogStash::Util::FileTools:Module
       process_downloads at /logstash/lib/logstash/util/filetools.rb:180
                    each at file:/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/java_ext/java.util.rb:7
       process_downloads at /logstash/lib/logstash/util/filetools.rb:162
              setup_hook at /logstash/lib/logstash/pluginmanager/vendor.rb:13
                    call at org/jruby/RubyProc.java:271
  run_post_install_hooks at /logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:273
                    each at org/jruby/RubyArray.java:1613
  run_post_install_hooks at /logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:272
                 install at /logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:237
                 install at /logstash/vendor/jruby/lib/ruby/shared/rubygems/request_set.rb:75
                    each at org/jruby/RubyArray.java:1613
                 install at /logstash/vendor/jruby/lib/ruby/shared/rubygems/request_set.rb:62
                 install at /logstash/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:363
              update_gem at /logstash/lib/logstash/pluginmanager/update.rb:70
                 execute at /logstash/lib/logstash/pluginmanager/update.rb:36
                    each at org/jruby/RubyArray.java:1613
                 execute at /logstash/lib/logstash/pluginmanager/update.rb:36
                     run at /logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/command.rb:67
                 execute at /logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.3/lib/clamp/subcommand/execution.rb:11
                     run at /logstash/lib/logstash/runner.rb:144
                    call at org/jruby/RubyProc.java:271
                     run at /logstash/lib/logstash/runner.rb:171
                    call at org/jruby/RubyProc.java:271
              initialize at /logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/task.rb:12

**Comment by suyograo** [comment]
hi @rabidscorpio, we recently fixed this in https://github.com/elasticsearch/logstash/pull/2572. Unfortunately this requires you to use the latest version of Logstash core. We are working on a RC1 release (soon) which will include this fix

**Comment by jordansissel** [comment]
From the last comment it sounds like this was fixed. Gonna close this. Feel free to open a new ticket if this continues to be a problem.
