### ISSUE TITLE
Implement ECS-Compatibility Mode

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-filter-geoip#163]
As a part of the effort to make plugins able to run in an ECS-Compatible manner
by default in an upcoming release of Logstash, this plugin needs to implement
an ECS-Compatibility mode that does not implicitly use fields that conflict
with ECS.

Absent `target` directive, this plugin uses root-level field `geoip`,
which is _undefined_ in ECS and therefore has the possiblity of conflicting
with future versions of ECS. The plugin may benefit from an ECS-Compatibility
mode that requires the target to be set explicitly, ~by using the ECS-compatible
root-level `geo` object~ (edit: _"the geo fields are not expected to be used
directly at the top level."_), or otherwise reduces the risk of future conflict.

Additional analysis will need to be made to ensure the resulting object is also compatible with the [geo field type in ECS](https://www.elastic.co/guide/en/ecs/current/ecs-geo.html).

**Comment by kares** [comment]
Plugin will need to be aligned with [ES output](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/924) (default template for `geoip: ...` needs to be adjusted)

**Comment by yaauie** [comment]
| DB Field Name    | ECS Equivalent Subfield Name           |
| ---------------- | -------------------------------------- |
| `asn`            | _N/A_                                  |
| `as_org`         | _N/A_                                  |
| `city_name`      | `city_name`                            |
| `country_name`   | `country_name`                         |
| `continent_code` | _N/A_                                  |
| `continent_name` | `continent_name`                       |
| `country_code2`  | `country_iso_code`                     |
| `country_code3`  | _N/A_                                  |
| `ip`             | _N/A_                                  |
| `isp`            | _N/A_                                  |
| `postal_code`    | _N/A_                                  |
| `dma_code`       | _N/A_                                  |
| `region_name`    | `region_name`                          |
| `region_code`    | `region_iso_code`* (`WA` or `US-WA`)?  |
| `timezone`       | _N/A_                                  |
| `location`       | * SEE: `location.lat` & `location.lon` |
| `latitude`       | `location.lat`                         |
| `longitude`      | `location.lon`                         |
| `organization`   | _N/A_                                  |
| _it depends_     | `name`                                 |

**Comment by jeffrysleddens** [comment]
asn and as_org map to the autonomous systems fields (https://www.elastic.co/guide/en/ecs/current/ecs-as.html) as.number and as.organization.name respectivly
