### ISSUE TITLE
Remove the logic to include in the vendored files when creating the gem

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-filter-geoip#18]
When we are building the gem we are vendoring the files in the gem, we should rely on `file-dependencies` (https://github.com/electrical/file-dependencies/)

see https://github.com/elasticsearch/logstash/issues/2649

**Comment by talevy** [comment]
@ph I think it is OK to leave the vendoring logic locally so we don't add another dependency. it is fairly low overhead and explicit to maintain. what do you think?

I know you mentioned this same problem here: https://github.com/logstash-plugins/logstash-codec-collectd/issues/8

**Comment by ph** [comment]
I am ok with that.
