### ISSUE TITLE
"fields" doesn't work as expected for "location"

### ISSUE THREAD

**Issue by volter** [logstash-plugins/logstash-filter-geoip#19]
What is happening:

If you don't specify "longitude" and "latitude" in "fields", "location" is not created, even if you requested it in "fields".

Why is it happening:

"location" is constructed from "longitude" and "latitude" property of the event.

Expected behaviour:

Construct "location" regardless whether "longitude" and/or "latitude" are specified in "fields".

**Comment by jordansissel** [comment]
Agreed on the behavior being a bug.

**Comment by jordansissel** [comment]
Fixed by #20/#22, thank you! :)
