### ISSUE TITLE
Enable the use of MaxMind GeoIP2-Anonymous-IP database in the plugin

### ISSUE THREAD

**Issue by RiverCitySecDevOps** [logstash-plugins/logstash-filter-geoip#212]
An Anonymous IP database PR from 2018 was created: https://github.com/logstash-plugins/logstash-filter-geoip/pull/141

This was never merged back into the plugin. Support for the Anonymous IP database would be greatly appreciated and help support the paid MaxMind databases .

Usage of the database can be found [in MaxMind's GitHub](https://github.com/maxmind/GeoIP2-java#anonymous-ip) and full documentation can be found on [MaxMind's GeoIP2 Anonymous IP Databases page](https://dev.maxmind.com/geoip/docs/databases/anonymous-ip?lang=en#binary-database)

**Comment by benatbermejo** [comment]
+1 Would be nice for fraud detection use case.
