### ISSUE TITLE
GeoLite2 support

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-geoip#23]
(This issue was originally filed by @coder3000 at https://github.com/elastic/logstash/issues/1709)

---

Will logstash support geolite2 in future? I am using geolite2 on server-side and there is some discrepancy caused by logstash. Specifying geolite2 db in geoip filter spits out errors.

**Comment by garyelephant** [comment]
I developed a [Logstash-filter-geoip2](https://github.com/garyelephant/logstash-filter-geoip2) to support maxmindDB/geoip2.
Actually the code was based on `logstash-filter-geoip`, I replaced its main code with official maxmindDB Java API.
It currently only support city information by now.
Note:This plugin doesn't include any maxmindDB database file.My Company has it but it will not be open to external.
I hope we can improve this plugin together.

**Comment by slatemine** [comment]
I was thinking of doing the same thing,  could not see your code 404. Makes sense to build off the java api and support the various databases. Looking at geopip it should be a pretty trivial extension.

**Comment by ejectck** [comment]
Voting for GeoIP2 support in logstash-filter-geoip

**Comment by dfaropennetwork** [comment]
+1

**Comment by markwalkom** [comment]
+1

**Comment by mshirley** [comment]
+1

**Comment by KrisBuytaert** [comment]
+2

**Comment by yinchuan** [comment]
+1

**Comment by hp197** [comment]
https://github.com/hp197/logstash-filter-geoip2

This is a initial release and *WILL*  contain bugs.

**Comment by xbgmsharp** [comment]
:+1:

**Comment by wuyouzi** [comment]
@hp197  :+1:

**Comment by dforste** [comment]
+1

**Comment by garyelephant** [comment]
Sorry for deleting my [Logstash-filter-geoip2](https://github.com/garyelephant/logstash-filter-geoip2) project a year ago.Recently I recreated this project on Github.

*    This plugin has been running in my company's logstash instance more than one year with 2TB+ data every day.

*    [GeoLite2-City.mmdb](http://dev.maxmind.com/geoip/geoip2/geolite2/) from official free maxmindDB database is included.

*    I will publish a gem to rubygems.org to make installation as easy as other logstash plugins in the future.

`Need your feedback!`

**Comment by suyograo** [comment]
@garyelephant thanks. Why not create a PR for this repo so we can update this plugin to GeoLite2? We can bump to major version then?

Its confusing to have 2 plugins for geoip

**Comment by garyelephant** [comment]
@suyograo Make sense.I'm going to do this.

**Comment by ebuildy** [comment]
Great new!

Why not this library https://github.com/yhirose/maxminddb? it's pure ruby i believe.

Thanks,

**Comment by suyograo** [comment]
@garyelephant woot! let us know if you need help. We added caching in #40.. so that and your java implementation would improve the performance here.

@ebuildy we could, but at this time, LS does not work well with anything other than JRuby, so why not use the java implementation?

**Comment by ebuildy** [comment]
Ya agree, I don't know ;-) 

I hope this new version will preload database like geoip can do (https://github.com/cjheath/geoip/blob/master/lib/geoip.rb#L239) I saw a big improvement with that.

**Comment by ebuildy** [comment]
Hello any update on this? cheers

**Comment by jordansissel** [comment]
@ebuildy nothing I'm aware of. I searched for geoip2 on open PRs in this repo and didn't find anything.

**Comment by ebuildy** [comment]
Just tested geoip2, works fine as expected.

BTW, a good point => https://github.com/maxmind/GeoIP2-java#multi-threaded-use , this mean we don't need the ``Thread.current[@threadkey]`` trick, isn'it? (and share maxmind build-in cache between threads)

**Comment by garyelephant** [comment]
@ebuildy Thanks for you advice, I will improve the codes.

**Comment by ebuildy** [comment]
@garyelephant I did a small fork (https://github.com/ebuildy/logstash-filter-geoip2), moved to 2.4.0 because they added built-in cache.

BTW 2.6.0 is not compatible with logstash 2.2 because jackson library conflict (should be fixed with logstash 3.0).

**Comment by suyograo** [comment]
@ebuildy @garyelephant I am super excited to get this change into this plugin. Any ETA? :)

**Comment by ebuildy** [comment]
You can give a try to my or garyelephant fork, any advice about how to integrate Java JAR vendor?

I am finishing https://github.com/logstash-plugins/logstash-filter-useragent/pull/23 PR, then I could spend some time on it.

**Comment by garyelephant** [comment]
@ebuildy Good, I'm going to make a pull request to logstash-filter-geoip this week.

**Comment by ebuildy** [comment]
Great!

**Comment by ebuildy** [comment]
Hello, I have almost finish to implement all former fields:

https://github.com/ebuildy/logstash-filter-geoip2/blob/master/lib/logstash/filters/geoip.rb

Still a few issues on spec tests, but I am on it!

**Comment by garyelephant** [comment]
Thanks @ebuildy , I forked this repo and update its code to geoip2, Could you please commit your code in [this repo](https://github.com/garyelephant/logstash-filter-geoip), by pull request. After that, I can make a pull request to this repo to make geoip2 available to community.

**Comment by ebuildy** [comment]
Maybe we could copy field names from:

https://github.com/elastic/elasticsearch/blob/master/plugins/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/GeoIpProcessor.java

?

**Comment by garyelephant** [comment]
#64 I made a PR, Please take a look, @ebuildy ,@suyograo

**Comment by pemontto** [comment]
People also use this plugin with the legacy ASN database. The ASN number and names lookups are now provided by same geoip2 database. Can these please also be considered in the legacy naming support?

e.g.
```json
"dest_asn": {
  "number": "AS16509",
  "asn": "Amazon.com, Inc."
}
```

**Comment by IngaFeick** [comment]
+1

**Comment by suyograo** [comment]
GeoIP2 and IPv6 support has been added in version 3.0.0 of this plugin for LS versions <= 2.x and 4.0.0 for LS version >= 5.x. Many thanks to @garyelephant and @ebuildy for helping out!
