### ISSUE TITLE
Multiple geoip filters causes Logstash to freeze

### ISSUE THREAD

**Issue by warpedgeoid** [logstash-plugins/logstash-filter-geoip#25]
I've run across an issue that causes logstash to freeze while trying to use two geoip filters consecutively with two different Maxmind databases. If only one filter is used, no issue occurs. The logstash process will not respond to shutdown messages and must be killed manually.

This is on CentOS 7 x64 with Logstash 1.5.0 and no external plugins installed. I read a previous bug report that was marked as fixed for version 1.4.0, so I'm trying to determine if this is indeed a regression or if I am doing something incorrectly in my config.

Here is the offending portion of my config:

```ruby
  if [prog] =~ /^filterlog$/ {  
    mutate {
      add_tag => ["firewall"]
      remove_field => [ "msg", "datetime" ]      
    }
    grok {
      patterns_dir => "/etc/logstash/patterns/*"
      match => [ "message", "%{LOG_DATA}%{IP_SPECIFIC_DATA}%{IP_DATA}%{PROTOCOL_DATA}" ]
    }
    mutate {
      lowercase => [ 'proto' ]
    }
    # do GeoIP lookup for the Country, State and City.
    geoip {
      source => "src_ip"
    }
    # do GeoIP lookup for the ASN/ISP information.
    geoip {
      database => "/etc/logstash/geoip/GeoIPASNum.dat"
      source => "src_ip"
    }
   }
```

Any help is greatly appreciated!

**Comment by philhagen** [comment]
Confirming this behavior as well.  However, I've found the issue seems to be with the ASN database, not just multiple geoip{} filter operations.  I removed the City/State/etc lookup portion and it still locks up.
I've verified that the ASN database is the same between a functioning 1.4 instance and the hanging 1.5 instance.

**Comment by philhagen** [comment]
@warpedgeoid I had identical behavior, which was remedied by updating plugin to v 0.1.10.  `bin/plugin update logstash-filter-geoip` did the trick.
