### ISSUE TITLE
IPv6 causes crash

### ISSUE THREAD

**Issue by NoodlesNZ** [logstash-plugins/logstash-filter-geoip#33]
Afaik there was a similar crash, but it had been fixed. I'm running the latest plugin (Logstash 1.5.2 and ./bin/plugin update logstash-filter-geoip says it's up to date).

This is the config I'm trying to use to get around not having native ipv6 support:

```
if [clientip] =~ /:/ {
    geoip {
        database => "/usr/share/GeoIP/GeoLiteCityv6.dat"
        source => "clientip"
    }
} else {
    geoip {
        database => "/usr/share/GeoIP/GeoLiteCity.dat"
        source => "clientip"
    }
}
```
And this is the error it spits out:

```
{:timestamp=>"2015-07-09T22:41:27.710000-0500", :message=>"The error reported is: \n  uninitialized constant LogStash::Filters::GeoIP::RuntimeException"}
```

If I remove the first geoip then it works fine (no ipv6 lookups).

**Comment by setaou** [comment]
This problem is still present in logstash 1.5.4.

**Comment by suyograo** [comment]
GeoIP2 and IPv6 support has been added in version 3.0.0 of this plugin.
