### ISSUE TITLE
Geoip configuration problems

### ISSUE THREAD

**Issue by dfaropennetwork** [logstash-plugins/logstash-filter-geoip#37]
Hi All

I've problems with mi geoip ip configuration, i've kibana 4.1.1 with logstash 1.5.3 and apache 2.4.

This is my personalized geoip file configuration on logstash, i called 12-geoip.conf :

filter {
  if [type] == "apache_access" {
    grok {
      match => { "message" => "%{COMMONAPACHELOG}" } 

  }
   geoip {
      source => "clientip"
      target => "geoip.location"
      database => "/etc/logstash/GeoLiteCity.dat"
      add_field => [ "[geoip.location][coordinates]", "%{[geoip.location][longitude]}" ]
      add_field => [ "[geoip.location][coordinates]", "%{[geoip.location][latitude]}"  ]
    }
    mutate {
      convert => [ "[geoip.location][coordinates]", "float"]
    }
  }
 }

Mi apache configuration on other file
filter {
  if [type] == "apache" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
      add_field => [ "received_from", "%{host}" ]
   }
  }
 }

My problem is that Kibana don't appears the "geoip" field, but clientip, hostname, etc.... appears. 

Part of my logstash-forwarder configuration

    {
      "paths": [
        "/var/log/apache2/*error.log",
        "/var/log/apache2/*access-ssl.log"
       ],
      "fields": { "type": "apache" }
    },
    {
      "paths": [
        "/var/log/apache2/*access.log"
       ],
      "fields": { "type": "apache_access" }
     }
  ]
}

And my logstash-forwarder registered events:

2015/09/04 09:07:57.807119 Registrar: processing 5 events
2015/09/04 09:08:45.244783 Registrar: processing 2 events
2015/09/04 09:08:50.238178 Registrar: processing 2 events
2015/09/04 09:09:02.744967 Registrar: processing 1 events

Thax so much.

**Comment by dfaropennetwork** [comment]
Anyone??

**Comment by pioneerit** [comment]
I have the similar problems.
I can add that my fields has mapping in template. And I can see them as IP type in Kibana.
But geoip field is empty.
Haven't found where is a problem yet.
I tested it on 1.4.2 logstash verision. And latest 1.5.4
Both version doesn't work for geoip

**Comment by pioneerit** [comment]
I've found my problem, I don't know right format for source in geoip filter.
I've run few test - when I have record on top level in my JSON everything works fine.

But I have:
@fields.remote_addr

I checked remote_addr, @fields.remote_addr, fields.remote_addr, ['fields']['remote_addr'].
All of them don't work for me.
Does anyone know right format?

**Comment by untergeek** [comment]
Sorry to hear you're having problems.  This issue should not be here, but in https://discuss.elastic.co in the Logstash section.

**Comment by pioneerit** [comment]
Thanks for link to https://discuss.elastic.co
I found solution with bruteforce :)
And after I found that link with explanation - https://logstash.jira.com/browse/LOGSTASH-2128

@dfaropennetwork, I think you should try simple config, because all other values by default exist without any mutate and etc...
Replace geoip and mutate with this:
geoip {
  source => "clientip"
  database => "/etc/logstash/GeoLiteCity.dat"
}

And if you will have any problems, join to https://discuss.elastic.co

**Comment by andrewvc** [comment]
Glad you found a solution @pioneerit !

**Comment by dfaropennetwork** [comment]
My resolution for help the people

The problems was on the index template, i needed one and i had to select manual mapping for geoip fields, but all this problems are resolved in the elasticsearch version 2.0, instead i put my index mapping for help the people with old versions, 1.4.* etc...

Template.json

{
  "order" : 0,
  "template" : "mytemplate-*",
  "settings" : { "index.refresh_interval" : "5s" "number_of_shards": "2"},
  "mappings" : {
    "_default_" : {
      "dynamic_templates" : [
        {
          "message_field" : {
            "mapping" : { "index" : "analyzed", "omit_norms" : true, "type" : "string" },
            "match_mapping_type" : "string",
            "match" : "message" }
          },
        {
          "string_fields" : {
            "mapping" : { "index" : "not_analyzed", "ignore_above" : 256, "type" : "string" },
            "match_mapping_type" : "string",
            "match" : "*" }
          }
       ],
      "properties" : {
        "geoip" : {
          "dynamic" : true,
          "path" : "full",
          "properties" : { "location" : { "type" : "geo_point" } },
          "type" : "object" },
        "@version" : { "index" : "not_analyzed", "type" : "string" }
      },
      "_all" : { "enabled" : true }
    }
  },
  "aliases" : { }
}


And the logstash configuration very important, file 30-lumberjack-output.conf for example

output {
  elasticsearch {
  host => localhost
  index => "mytemplate-%{+YYYY.MM.dd}"
  template => "/etc/logstash/mytemplate.json"
  template_name => "mytemplate-*"
  manage_template => "true"
  template_overwrite => "true"
}
  stdout { codec => rubydebug }
}
