### ISSUE TITLE
geoip filter is not parsing ip_adress

### ISSUE THREAD

**Issue by irenerong** [logstash-plugins/logstash-filter-geoip#48]
Hi guys,
i'm trying to parsing ip_adress with geoip filter , my data comes in form of "172.24.12.250:19552", so before passing the geopi filter, i use the mutate filter to get off the port
mutate {
		gsub=>[
			
			"IP_PORT","(.*\..*\..*\..*):.*","\1"
		]	
	}	

geoip{
		source=> 'IP_PORT'
		target=> 'geoip'
		add_tag=>['geoip']
	}

but after the gsub, geoip seems could not parsing the modified de ip adress.
my output is :
{
                  "message" => [
        [0] "01_W40,4,28.09.2015 02:10:10,Authentication Process,47152093228,Accepted,MRS0400CM,0119AA,4,CMSU0219,HOSTED,0,28.09.2015 02:10:02,Local,,,6F9976CAD5CCDB48CCA679783938FBAC77872776,MAC,CM,A/MRS/T/1/TRN/1,GS,1ASIGDC04,1A/CMG/G-CM,172.25.57.244,YKUISWVHSHUO0O6COWAGSG4"
    ],
                 "@version" => "1",
               "@timestamp" => "2015-10-26T16:15:25.371Z",
                     "host" => "NCEVC-03441",
                     "path" => "/home/admin/testcuthistory_short.csv",
                 "P_PERIOD" => "01_W40",
                  "CONTEXT" => "4",
               "TIME_STAMP" => "28.09.2015 02:10:10",
      "FUNCTION_IDENTIFIER" => "Authentication Process",
                  "LINE_ID" => "47152093228",
                   "ACTION" => "Accepted",
                      "OFC" => "MRS",
                     "SIGN" => "0119AA",
             "ORGANIZATION" => "4",
                  "USER_ID" => "CMSU0219",
               "USER_TYlPE" => "HOSTED",
    "UNSUCCESSFUL_ATTEMPTS" => "0",
         "LAST_SIGNIN_DATE" => "28.09.2015 02:10:02",
           "DATA_PROPERTY1" => "Local",
           "DATA_PROPERTY2" => nil,
             "SHORT_DETAIL" => nil,
           "LOCATION_VALUE" => "6F9976CAD5CCDB48CCA679783938FBAC77872776",
            "LOCATION_TYPE" => "MAC",
              "APPLICATION" => "CM",
            "FULL_LOCATION" => "A/MRS/T/1/TRN/1",
                "DUTY_CODE" => "GS",
               "TARGET_SAP" => "1ASIGDC04",
                    "CLAPP" => "1A/CMG/G-CM",
                  "IP_PORT" => "172.25.57.244",
                    "DCXID" => "YKUISWVHSHUO0O6COWAGSG4"
}
PS: the input file is csv file just incase you wonder.

could someone tell me the reason?
thanks

**Comment by untergeek** [comment]
Because you're including the port.  The `geoip` filter will only accept an IPv4 address.  

You must truncate the port off of your IP before passing it to the filter for it to work properly.

**Comment by untergeek** [comment]
Disregard the last bit.  I only saw the name, `IP_PORT`.

Your _actual_ problem is that you're using a protected, non-routable IP address.

All IP addresses between 172.16.0.0 - 172.31.255.255 are non-routable.  There would be no GeoIP associated with this address because anyone can use this inside their organization.

If you need to associate an IP with this, see [this example](https://coolacid.net/ossim-logstash/275-generating-a-local-maxmind-geoip-db).

**Comment by untergeek** [comment]
Other non-routable blocks include: `10.0.0.0 - 10.255.255.255` and `192.168.0.0 - 192.168.255.255`
