### ISSUE TITLE
allow the inclusion/exclusion of the "extra" location field

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-filter-geoip#6]
The `location` field is dynamically added to the geoip structure when both `latitude` and `longitude` fields are present https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L141-L144 to provide a GeoJSON compatible fields structure.

The `fields` config https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L48 should also support including/excluding this `location` field to avoid unnecessary duplicate info.

**Comment by jordansissel** [comment]
@colinsurprenant +1 on this change. This change will break backwards compat, though, so we'll probably want a big version bump.

**Comment by colinsurprenant** [comment]
old issue followup: should we plan this for 5.0? I'll put P1 to make sure we assess this quickly.

**Comment by jordansissel** [comment]
I think this is done for a while now, closing: https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/lib/logstash/filters/geoip.rb#L218-L219
