### ISSUE TITLE
v3.0.0-beta Sometimes returns nil value for location field

### ISSUE THREAD

**Issue by ebuildy** [logstash-plugins/logstash-filter-geoip#70]
Testing new version with Maxmind geoIp2 Java, for some IP adresses:

- 113.208.89.219
- 67.209.98.194
- 217.15.165.185

The plugins returns a ``nil`` values for all fields, which is OK because elasticsearch will cast nil as empty string, but in the case of ``location`` field, if you setup ``geo`` mapping, ES will raise a ``mapping_exception`` error, hence document is not indexed.

I know a solution is to use https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html. But I think the plugin should not include ``location`` field if it contains nil values.

**Comment by suyograo** [comment]
@ebuildy can we remove location when it is `nil` and also add a tag which indicates nil was removed ? This would help users analyze the result set at a later time

**Comment by ebuildy** [comment]
Seems a good deal! I will  do a PR soon  , thanks

**Comment by suyograo** [comment]
I encountered the same issue while parsing this log line

```
109.236.151.146 - - [11/Sep/2014:13:13:41 +0000] "GET /images/googledotcom.png HTTP/1.1" 200 65748 "http://www.google.com.ly/search?q=wwwgoogle&client=tablet-android-samsung&hl=ar&v=141278776&tbm=isch&source=lnms&sa=X&ei=9F4nU-2uLPSh7AbZxYHoBw&ved=0CAcQ_AUoAA&biw=600&bih=1024&dpr=1" "Mozilla/5.0 (Linux; U; Android 4.0.3; ar-ae; GT-P3100 Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30"
```

GeoIP legacy was able to resolve it:

```
"geoip" => {
                    "ip" => "109.236.151.146",
         "country_code2" => "DE",
         "country_code3" => "DEU",
          "country_name" => "Germany",
        "continent_code" => "EU",
              "latitude" => 51.0,
             "longitude" => 9.0,
              "timezone" => "Europe/Berlin",
              "location" => [
            [0] 9.0,
            [1] 51.0
        ]
    }
```

But GeoIP2 had `nils` for all fields:

```
"geoip" => {
              "timezone" => nil,
                    "ip" => "109.236.151.146",
              "latitude" => nil,
        "continent_code" => nil,
             "city_name" => nil,
         "country_code2" => nil,
          "country_name" => nil,
              "dma_code" => nil,
         "country_code3" => nil,
           "region_name" => nil,
              "location" => [
            [0] nil,
            [1] nil
        ],
           "postal_code" => nil,
             "longitude" => nil,
           "region_code" => nil
    }
```

Using https://www.iplocation.net/ I get mixed results.. maxmind does not resolve this IP to a location..
