### ISSUE TITLE
Logstash 5.x no longer supports .dat format Geo Databases

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-filter-geoip#90]
Testing on Logstash 5.0-alpha4, noticing that `.dat` version DBs are no longer supported, and now the `.mmdb` format is required.    

@suyograo This issue is meant to track updates to breaking changes & docs.

```
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1
Invalid setting for geoip filter plugin:

  filter {
    geoip {
      # This setting must be a path
      # File does not exist or cannot be opened /tmp/GeoLiteCity.dat
      database => ["/tmp/GeoLiteCity.dat"]
      ...
    }
  } {:level=>:error}
fetched an invalid config {:config=>"input {\n\tstdin {}\n}\nfilter {\n        geoip {\n            database => [\"/tmp/GeoLiteCity.dat\"]\n\t    source => \"message\"\n        }\n}\noutput {\n \tstdout {}\n}\n\n", :reason=>"Something is wrong with your configuration.", :level=>:error}
```

**Comment by mostolog** [comment]
As I asked in https://discuss.elastic.co/t/logstash-5-0-0-alpha4-geoip-something-is-wrong-with-your-configuration/55991 we are also having this issue.

**Comment by PhaedrusTheGreek** [comment]
@suyograo did our breaking changes docs ever get updated on this?

**Comment by rsaeks** [comment]
Ran into this issue as well and have switched to the new format. However, with the new format the ability to pull back ASN data is gone in the basic free database file.

**Comment by slalomnut** [comment]
I ran into this during the upgrade.  No more ASN?? :(  According to MaxMind, there is no roadmap for a mmdb version of GeoIPASNum.  Will backwards compatibility be implemented or did have we lost this feature for good?

**Comment by jordansissel** [comment]
Regarding ASN lookups, we may need to roll our own thing if a replacement
can't be found. If anyone has suggestions, I am open.

**Comment by slalomnut** [comment]
Any chance of using both MaxMind API's controlled by a config flag?

**Comment by sliddjur** [comment]
Maybe someone can create a mmdb database from the IPV6/IPV4  csv files with this https://github.com/maxmind/MaxMind-DB-Writer-perl ?

**Comment by sh4t** [comment]
I pay for the sub to `GeoIP2-ISP.mmdb` and would like to see it implemented.  How can I help @jordansissel

**Comment by mihu** [comment]
Wow, that's quite a show stopper for upgrading from logstash 2.4. What about porting the old plugin to new logstash just for the sake of accessing of older databases?

**Comment by jordansissel** [comment]
Closing in favor of #91

**Comment by Bairyramu** [comment]
Hi All I am facing the problem of geo location recently i have installed elasticsearch, kibana and logstash of 7.1.0 logstash i mention the 
geoip {
        source => "clientip"
        target => geoip
        database => "elasticsearch-7.1.0/modules/ingest-geoip/GeoLite2-City.mmdb"
        add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
        add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}" ]
}

but i am getting error called
  filter {
    geoip {
      # This setting must be a path
      # File does not exist or cannot be opened elasticsearch-7.1.0/modules/ingest-geoip/GeoLite2-City.mmdb
      database => "elasticsearch-7.1.0/modules/ingest-geoip/GeoLite2-City.mmdb"
      ...
    }
  }
i was searching regarding this but i did not get any clear result.
could you please tell me what to do.

Thanks and Regards
Ramu Bairy
