### ISSUE TITLE
Add support for GeoIP2-ISP database

### ISSUE THREAD

**Issue by ejectck** [logstash-plugins/logstash-filter-geoip#91]
As written in comment to geoip.rb  "The path to the GeoLite2 database file which Logstash should use. Only City database is supported by now".

As for support Legacy  database dropped in geoip, for me there is no way to get information from GeoIPASNum.dat (legacy) or GeoIP2-ISP.mmdb (new format) databases to get information about ASNum by IP.

Dropping support for Legacy and not adding support for new database is quite big problem for me.

**Comment by imriz** [comment]
Hi,

I encountered this today too.
I've patched the plugin to allow you to use the ISP database.
See PR #94

**Comment by IngaFeick** [comment]
+1

**Comment by briangruber** [comment]
+1

**Comment by tomsommer** [comment]
ISP support is documented but not implemented? 
https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-database

+1

**Comment by sh4t** [comment]
They do have ISP-ASN database as .mmdb; just not available publicly to my knowledge.  It is available in the legacy format, and .mmdb format to paying subscribers.

**Comment by SMAPPER** [comment]
Any idea of if/when this may be put into general availability?

**Comment by jordansissel** [comment]
@SMAPPER please try to not comment on the same issue in multiple places (reference: https://github.com/logstash-plugins/logstash-filter-geoip/issues/96#issuecomment-284064208 and https://github.com/logstash-plugins/logstash-filter-geoip/issues/91#issuecomment-284064376).

If you want updates on this issue, I recommend watching this issue in Github:

![image](https://cloud.githubusercontent.com/assets/131818/23570600/c326f244-0019-11e7-95ed-d9257869175d.png)

**Comment by acchen97** [comment]
An update for those encountering this: we now have a plan for resolving ISP and ASN lookups. Feel free to provide additional feedback on this issue https://github.com/logstash-plugins/logstash-filter-geoip/issues/110.

**Comment by acchen97** [comment]
Closing as this has been delivered with [geoip filter v4.1.0](https://github.com/logstash-plugins/logstash-filter-geoip/pull/111).
